// <auto-generated />
using System;
using CV_Projekt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Projekt.Migrations
{
    [DbContext(typeof(CvContext))]
    partial class CvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CV_Projekt.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerId = "1",
                            Skills = "[\"Projektledning\",\"CSS\",\"HTML\"]",
                            Views = 10
                        },
                        new
                        {
                            Id = 2,
                            OwnerId = "3",
                            Skills = "[\"Grafisk design\",\"Pedagogik\"]",
                            Views = 11
                        },
                        new
                        {
                            Id = 3,
                            OwnerId = "2",
                            Skills = "[\"Omv\\u00E5rdnad\",\"Kommunikation\"]",
                            Views = 15
                        },
                        new
                        {
                            Id = 4,
                            OwnerId = "4",
                            Skills = "[\"Eventplanering\",\"Samordning\"]",
                            Views = 8
                        },
                        new
                        {
                            Id = 5,
                            OwnerId = "5",
                            Skills = "[\"Ingenj\\u00F6rskonst\",\"Produktutveckling\"]",
                            Views = 12
                        },
                        new
                        {
                            Id = 6,
                            OwnerId = "6",
                            Skills = "[\"Forskning\",\"Biomedicin\"]",
                            Views = 9
                        },
                        new
                        {
                            Id = 7,
                            OwnerId = "7",
                            Skills = "[\"AI-utveckling\",\"Python\",\"Machine Learning\"]",
                            Views = 20
                        },
                        new
                        {
                            Id = 8,
                            OwnerId = "8",
                            Skills = "[\"Milj\\u00F6skydd\",\"Administration\"]",
                            Views = 14
                        },
                        new
                        {
                            Id = 9,
                            OwnerId = "9",
                            Skills = "[\"Undervisning\",\"Kursutveckling\"]",
                            Views = 18
                        },
                        new
                        {
                            Id = 10,
                            OwnerId = "10",
                            Skills = "[\"Patientv\\u00E5rd\",\"Ledarskap\"]",
                            Views = 25
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.ContactInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rullgatan 24A",
                            Phone = "0723892311"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Johanneslunden 7",
                            Phone = "0724873928"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kolagränd 23",
                            Phone = "0809483729"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mossvägen 15",
                            Phone = "0738452390"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bäckstigen 12B",
                            Phone = "0709847328"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kullavägen 8",
                            Phone = "0762938475"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Tallbacken 4",
                            Phone = "0701938476"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Lärkträdsvägen 10",
                            Phone = "0739487261"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Allegatan 14C",
                            Phone = "0723847569"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Stenvägen 5A",
                            Phone = "0768273945"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Experiences");

                    b.HasDiscriminator().HasValue("Experience");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CV_Projekt.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReceiverDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SenderDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hej på dig! Hur är det med dig?",
                            Date = new DateTime(2020, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "2",
                            SenderDelete = false,
                            SenderId = "1",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "Missade att du skrev, förlåt.",
                            Date = new DateTime(2020, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "1",
                            SenderDelete = false,
                            SenderId = "2",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 3,
                            Content = "Ska vi ta en lunch imorgon?",
                            Date = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "1",
                            SenderDelete = false,
                            SenderId = "3",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 4,
                            Content = "Tack för att du hjälpte mig med projektet.",
                            Date = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "3",
                            SenderDelete = false,
                            SenderId = "1",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 5,
                            Content = "Kan du kika på dokumentet jag skickade?",
                            Date = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "5",
                            SenderDelete = false,
                            SenderId = "4",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 6,
                            Content = "Jag har lagt till några kommentarer i ditt utkast.",
                            Date = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "4",
                            SenderDelete = false,
                            SenderId = "5",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 7,
                            Content = "Glöm inte mötet imorgon kl. 10.",
                            Date = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "7",
                            SenderDelete = false,
                            SenderId = "6",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 8,
                            Content = "Har du hunnit förbereda presentationen?",
                            Date = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "6",
                            SenderDelete = false,
                            SenderId = "7",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 9,
                            Content = "Grattis på födelsedagen!",
                            Date = new DateTime(2020, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "9",
                            SenderDelete = false,
                            SenderId = "8",
                            SenderName = "",
                            isRead = false
                        },
                        new
                        {
                            Id = 10,
                            Content = "Ha en trevlig helg! Vi hörs på måndag.",
                            Date = new DateTime(2020, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiverDelete = false,
                            ReceiverId = "10",
                            SenderDelete = false,
                            SenderId = "9",
                            SenderName = "",
                            isRead = false
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = "1",
                            Description = "En app för att optimera postleveranser.",
                            EndDate = new DateTime(2011, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2010, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tidtabell för postnord"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = "3",
                            Description = "Ett bokningssystem för SJ-resor.",
                            EndDate = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SJ Bokningssystem"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = "2",
                            Description = "En databas för miljöövervakning och analys.",
                            EndDate = new DateTime(2016, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2015, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Miljödatabas"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = "4",
                            Description = "Ett verktyg för att planera och hantera evenemang.",
                            EndDate = new DateTime(2019, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eventplaneringssystem"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = "7",
                            Description = "En AI-baserad chatbot för kundsupport.",
                            EndDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI-driven chatbot"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = "5",
                            Description = "En app för att organisera och schemalägga uppgifter.",
                            EndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Virtuell assistent"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = "6",
                            Description = "Ett system för analys av biomedicinska data.",
                            EndDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Biomedicinsk analys"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = "8",
                            Description = "En plattform för att hantera och driva e-handel.",
                            EndDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "E-handelsplattform"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = "9",
                            Description = "Ett skattesystem med automatiserad rapportering.",
                            EndDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avancerat skattesystem"
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = "10",
                            Description = "En lösning för fjärrmedicinska konsultationer.",
                            EndDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Telemedicinplattform"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descriptor = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Descriptor = "Medicin"
                        },
                        new
                        {
                            Id = 3,
                            Descriptor = "Omvårdnad"
                        },
                        new
                        {
                            Id = 4,
                            Descriptor = "Transport"
                        },
                        new
                        {
                            Id = 5,
                            Descriptor = "Utbildning"
                        },
                        new
                        {
                            Id = 6,
                            Descriptor = "Forskning"
                        },
                        new
                        {
                            Id = 7,
                            Descriptor = "Miljö"
                        },
                        new
                        {
                            Id = 8,
                            Descriptor = "Kultur"
                        },
                        new
                        {
                            Id = 9,
                            Descriptor = "Sport"
                        },
                        new
                        {
                            Id = 10,
                            Descriptor = "Ekonomi"
                        },
                        new
                        {
                            Id = 11,
                            Descriptor = "Teknik"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InformationId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InformationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb5efd79-729f-43d7-bcda-853c0b3ac4ec",
                            Email = "alicean12@live.se",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            InformationId = 1,
                            LastName = "Andersson",
                            LockoutEnabled = false,
                            NormalizedEmail = "alicean12@live.se",
                            NormalizedUserName = "alicean12@live.se",
                            Password = "P@ssword123",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUxZpQrnJ/FMRRy0hrglRHleMYfvB6Ri/APLcTLNJhCcYXfn9mD/I0/AXKZP3j/6A==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "d2cc1534-8af6-4303-8dc8-d2f2490f758c",
                            TwoFactorEnabled = false,
                            UserName = "alicean12@live.se",
                            isActive = true,
                            isPrivate = true
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90e2c43f-6f14-488f-aa2c-f82578618c94",
                            Email = "bobbergstrom@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Bob",
                            InformationId = 2,
                            LastName = "Bergström",
                            LockoutEnabled = false,
                            NormalizedEmail = "bobbergstrom@gmail.com",
                            NormalizedUserName = "bobbergstrom@gmail.com",
                            Password = "P@ssword456",
                            PasswordHash = "AQAAAAIAAYagAAAAEGUb0GZys74/R9l17rO5LCzog6s9n98LwR2YL1a6WMIiYAUilWpPj9VKOcrhLRSJ+w==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "84bf2105-6025-4388-8c6b-d848c9172fc8",
                            TwoFactorEnabled = false,
                            UserName = "bobbergstrom@gmail.com",
                            isActive = true,
                            isPrivate = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e8bfc85-ea0b-4645-a5fb-94dfc46c0e6c",
                            Email = "charliec@live.se",
                            EmailConfirmed = false,
                            FirstName = "Charlie",
                            InformationId = 3,
                            LastName = "Carlsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "charliec@live.se",
                            NormalizedUserName = "charliec@live.se",
                            Password = "P@ssword789",
                            PasswordHash = "AQAAAAIAAYagAAAAENiH+XhE4aPH64outiL76KkUr4jzP2FxBG641CWUWO3xetOfqofsocMuOhwdYCpTpg==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "80cba2d1-bbcc-43ac-9033-3bf9fc75982a",
                            TwoFactorEnabled = false,
                            UserName = "charliec@live.se",
                            isActive = false,
                            isPrivate = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a6eb999-7807-407f-bff3-24f3da114584",
                            Email = "danield@outlook.com",
                            EmailConfirmed = false,
                            FirstName = "Daniel",
                            InformationId = 4,
                            LastName = "Davidsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "danield@outlook.com",
                            NormalizedUserName = "danield@outlook.com",
                            Password = "SecureP@ss1",
                            PasswordHash = "AQAAAAIAAYagAAAAEN36eM9vVErJDMcx2poILQtsq1wdLIPuFgibBnFkPZVdhex3nkC/BMQcHmuwLnLOUA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "ff7f77bf-da6e-49a4-8df5-9c7c69d460a1",
                            TwoFactorEnabled = false,
                            UserName = "danield@outlook.com",
                            isActive = true,
                            isPrivate = true
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6e1b0c2-4790-40f6-bd79-3276a2201948",
                            Email = "emily.evans@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            InformationId = 5,
                            LastName = "Evans",
                            LockoutEnabled = false,
                            NormalizedEmail = "emily.evans@hotmail.com",
                            NormalizedUserName = "emily.evans@hotmail.com",
                            Password = "MyP@ssword2",
                            PasswordHash = "AQAAAAIAAYagAAAAECglVzLR6Hu4TFgGCIhfju9Q9iLOfEqI5Kpu5STawq6kD+mDB8bfOvaOnMNXov16Yw==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "745f8302-3725-4282-be55-cc3ea25a68ff",
                            TwoFactorEnabled = false,
                            UserName = "emily.evans@hotmail.com",
                            isActive = true,
                            isPrivate = false
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f3297c8-5cad-4259-919b-cfd832b333f4",
                            Email = "frankfischer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Frank",
                            InformationId = 6,
                            LastName = "Fischer",
                            LockoutEnabled = false,
                            NormalizedEmail = "frankfischer@gmail.com",
                            NormalizedUserName = "frankfischer@gmail.com",
                            Password = "StrongP@ss3",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOvAH+aLsAy+hWfAdc9wPj9YpTnHgErqC36dNmABnQgAsklZqabl2aKknIj4B58uA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "ffc8f0e6-ac4a-44da-b39d-c40aad9cb580",
                            TwoFactorEnabled = false,
                            UserName = "frankfischer@gmail.com",
                            isActive = true,
                            isPrivate = true
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c111e49-9f93-4960-ac06-e0a99f726d2e",
                            Email = "grace.gustafsson@live.se",
                            EmailConfirmed = false,
                            FirstName = "Grace",
                            InformationId = 7,
                            LastName = "Gustafsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "grace.gustafsson@live.se",
                            NormalizedUserName = "grace.gustafsson@live.se",
                            Password = "GracefulP@ss4",
                            PasswordHash = "AQAAAAIAAYagAAAAEMT6hBU7BtXlyv/iC3IcgTwZoHQsxtW9uUvu+71BcEYpIyjxluzZqrT+2VYbplPikA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "a79992e8-3cb0-45a6-8835-797318980bf4",
                            TwoFactorEnabled = false,
                            UserName = "grace.gustafsson@live.se",
                            isActive = false,
                            isPrivate = false
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dabec090-dcf8-45b8-9ff7-c06f2819c305",
                            Email = "hanna.holm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Hanna",
                            InformationId = 8,
                            LastName = "Holm",
                            LockoutEnabled = false,
                            NormalizedEmail = "hanna.holm@gmail.com",
                            NormalizedUserName = "hanna.holm@gmail.com",
                            Password = "H@nnasP@ss5",
                            PasswordHash = "AQAAAAIAAYagAAAAEMWMPPXpi5/i82oW5JaXsrt3LbJFH8OMBb/IDKMSJAzuVx9q2tKt6NCz93IbBixxYw==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "a01d94fa-4752-4b15-8f4d-83fc301dadd3",
                            TwoFactorEnabled = false,
                            UserName = "hanna.holm@gmail.com",
                            isActive = true,
                            isPrivate = true
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02bdbafd-38d0-4f7f-9c12-a360be9bf252",
                            Email = "ian.ingemarsson@outlook.com",
                            EmailConfirmed = false,
                            FirstName = "Ian",
                            InformationId = 9,
                            LastName = "Ingemarsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ian.ingemarsson@outlook.com",
                            NormalizedUserName = "ian.ingemarsson@outlook.com",
                            Password = "I@nsSecure6",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwl4Lk612byCTBKyw/l85vnY9+JCS06oVRMfE0avjf65XGzwysCsA6rzjdqQOu2qg==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "074d2208-c9da-4fb0-b9de-1c0a341fd756",
                            TwoFactorEnabled = false,
                            UserName = "ian.ingemarsson@outlook.com",
                            isActive = true,
                            isPrivate = false
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0c4735a-e425-4ee5-8f15-367e425eaae0",
                            Email = "julia.jonsson@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Julia",
                            InformationId = 10,
                            LastName = "Jonsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "julia.jonsson@yahoo.com",
                            NormalizedUserName = "julia.jonsson@yahoo.com",
                            Password = "JuliasP@ss7",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3b3MZTnvIQ57Ks3TJUZU8wYfMXnk+S+EpRRLPv6od7lgkFs+R1XIf/W0H+X2jlnQ==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "~/images/profilepic_default.jpg",
                            SecurityStamp = "929f4309-db4e-4a54-ac94-99f7597aba07",
                            TwoFactorEnabled = false,
                            UserName = "julia.jonsson@yahoo.com",
                            isActive = false,
                            isPrivate = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<int>("JoinedProjectsId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JoinedProjectsId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TagsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TagUser");
                });

            modelBuilder.Entity("CV_Projekt.Models.Education", b =>
                {
                    b.HasBaseType("CV_Projekt.Models.Experience");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Education");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            City = "Örebro",
                            CvId = 2,
                            Description = "",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karolinska Gymnasiet",
                            StartDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Gymnasial",
                            Program = "Vård och omsorg"
                        },
                        new
                        {
                            Id = 22,
                            City = "Uppsala",
                            CvId = 3,
                            Description = "",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Uppsala Universitet",
                            StartDate = new DateTime(2010, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Kandidat",
                            Program = "Arkelogi"
                        },
                        new
                        {
                            Id = 23,
                            City = "Lund",
                            CvId = 4,
                            Description = "Specialisering inom hållbar utveckling",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lund Universitet",
                            StartDate = new DateTime(2018, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Master",
                            Program = "Miljövetenskap"
                        },
                        new
                        {
                            Id = 24,
                            City = "Göteborg",
                            CvId = 5,
                            Description = "Fokus på produktutveckling",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Chalmers Tekniska Högskola",
                            StartDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Master",
                            Program = "Maskinteknik"
                        },
                        new
                        {
                            Id = 25,
                            City = "Göteborg",
                            CvId = 6,
                            Description = "Med inriktning på etnologi",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Göteborg Universitet",
                            StartDate = new DateTime(2015, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Kandidat",
                            Program = "Kulturvetenskap"
                        },
                        new
                        {
                            Id = 26,
                            City = "Stockholm",
                            CvId = 7,
                            Description = "Med fokus på artificiell intelligens",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "KTH Royal Institute of Technology",
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Master",
                            Program = "Datavetenskap"
                        },
                        new
                        {
                            Id = 27,
                            City = "Stockholm",
                            CvId = 8,
                            Description = "Specialisering inom internationell handel",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Stockholms Universitet",
                            StartDate = new DateTime(2017, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Kandidat",
                            Program = "Ekonomi"
                        },
                        new
                        {
                            Id = 28,
                            City = "Umeå",
                            CvId = 9,
                            Description = "Studier inom ekologi och naturvård",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Umeå Universitet",
                            StartDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Kandidat",
                            Program = "Biologi"
                        },
                        new
                        {
                            Id = 29,
                            City = "Linköping",
                            CvId = 10,
                            Description = "Forskning inom kvantmekanik",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Linköping Universitet",
                            StartDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Doktorand",
                            Program = "Teknisk fysik"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.OtherExperience", b =>
                {
                    b.HasBaseType("CV_Projekt.Models.Experience");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OtherExperience");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Örebro",
                            CvId = 1,
                            EndDate = new DateTime(2017, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Örebro kommun",
                            StartDate = new DateTime(2016, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Praktik"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sköllersta",
                            CvId = 1,
                            Description = "En kurs i drejeri",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kävesta Folkhögskola",
                            StartDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Kurs"
                        },
                        new
                        {
                            Id = 3,
                            City = "Örebro",
                            CvId = 2,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Röda korset Örebro",
                            StartDate = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Volentärarbete"
                        },
                        new
                        {
                            Id = 4,
                            City = "Linköping",
                            CvId = 2,
                            Description = "Sommarjobb som forskningsassistent",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Linköping universitet",
                            StartDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Sommarjobb"
                        },
                        new
                        {
                            Id = 5,
                            City = "Stockholm",
                            CvId = 4,
                            Description = "Praktik inom medicinsk forskning",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karolinska Institutet",
                            StartDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Praktik"
                        },
                        new
                        {
                            Id = 6,
                            City = "Malmö",
                            CvId = 5,
                            Description = "Deltog i hjälparbete för flyktingar",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Svenska Röda Korset",
                            StartDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Volentärarbete"
                        },
                        new
                        {
                            Id = 7,
                            City = "Göteborg",
                            CvId = 6,
                            Description = "Kurs i hållbart byggande",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Chalmers Tekniska Högskola",
                            StartDate = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Kurs"
                        },
                        new
                        {
                            Id = 8,
                            City = "Örebro",
                            CvId = 7,
                            Description = "Projektarbete inom AI-utveckling",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Örebro Universitet",
                            StartDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Projektarbete"
                        },
                        new
                        {
                            Id = 9,
                            City = "Kiruna",
                            CvId = 8,
                            Description = "Volontärarbete inom miljöskydd",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Naturskyddsföreningen",
                            StartDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Volentärarbete"
                        },
                        new
                        {
                            Id = 10,
                            City = "Uppsala",
                            CvId = 9,
                            Description = "Deltog i en workshop om ledarskap",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Uppsala Universitet",
                            StartDate = new DateTime(2021, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Workshop"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.Work", b =>
                {
                    b.HasBaseType("CV_Projekt.Models.Experience");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Work");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            City = "Örebro",
                            CvId = 1,
                            Description = "Underhåller ett team i bageri/ungdomsgård",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Café Deed",
                            StartDate = new DateTime(2020, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Arbetsledare"
                        },
                        new
                        {
                            Id = 12,
                            City = "Uppsala",
                            CvId = 2,
                            Description = "Omvårdnad",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Uppsala Sjukhus",
                            StartDate = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Sjuksköterska"
                        },
                        new
                        {
                            Id = 13,
                            City = "Generisk stad",
                            CvId = 3,
                            Description = "Arbetsuppgifter",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Generiskt Företag",
                            StartDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Arbetstitel"
                        },
                        new
                        {
                            Id = 14,
                            City = "Stockholm",
                            CvId = 4,
                            Description = "Ansvarig för eventplanering och samordning",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Stockholms Stad",
                            StartDate = new DateTime(2018, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Eventkoordinator"
                        },
                        new
                        {
                            Id = 15,
                            City = "Arboga",
                            CvId = 5,
                            Description = "Utveckling och testning av nya bilmodeller",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Volvo Cars",
                            StartDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Ingenjör"
                        },
                        new
                        {
                            Id = 16,
                            City = "Stockholm",
                            CvId = 6,
                            Description = "Forskning inom biomedicin",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karolinska Institutet",
                            StartDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Forskningsassistent"
                        },
                        new
                        {
                            Id = 17,
                            City = "Örebro",
                            CvId = 7,
                            Description = "Hantering av deklarationer och rådgivning",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Skatteverket",
                            StartDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Handläggare"
                        },
                        new
                        {
                            Id = 18,
                            City = "Köping",
                            CvId = 8,
                            Description = "Administration och projektstöd",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Länsstyrelsen",
                            StartDate = new DateTime(2019, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Projektassistent"
                        },
                        new
                        {
                            Id = 19,
                            City = "Luleå",
                            CvId = 9,
                            Description = "Undervisning och kursutveckling",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Luleå Tekniska Universitet",
                            StartDate = new DateTime(2021, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Universitetslärare"
                        },
                        new
                        {
                            Id = 20,
                            City = "Skellefteå",
                            CvId = 10,
                            Description = "Patientvård och ledning av vårdteam",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Norrlands Universitetssjukhus",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Läkare"
                        });
                });

            modelBuilder.Entity("CV_Projekt.Models.CV", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", "Owner")
                        .WithOne()
                        .HasForeignKey("CV_Projekt.Models.CV", "OwnerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CV_Projekt.Models.Experience", b =>
                {
                    b.HasOne("CV_Projekt.Models.CV", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("CV_Projekt.Models.Message", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", "Receiver")
                        .WithMany("RecievedMessages")
                        .HasForeignKey("ReceiverId")
                        .IsRequired();

                    b.HasOne("CV_Projekt.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CV_Projekt.Models.Project", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CV_Projekt.Models.User", b =>
                {
                    b.HasOne("CV_Projekt.Models.ContactInformation", "ContactInformation")
                        .WithMany()
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactInformation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("CV_Projekt.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("JoinedProjectsId")
                        .IsRequired();

                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .IsRequired();
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.HasOne("CV_Projekt.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .IsRequired();

                    b.HasOne("CV_Projekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .IsRequired();
                });

            modelBuilder.Entity("CV_Projekt.Models.User", b =>
                {
                    b.Navigation("CreatedProjects");

                    b.Navigation("RecievedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
